### ISSUE TITLE
Inherit environment

### ISSUE THREAD

**Issue by dwieland** [iomarmochtar/gitlab-token-updater#6]
Hey there, thanks for this tool!

Is there any reason to not inherit the caller environment when calling the hooks?
Without that the hooks are really limited as important variables are missing (i.e. PATH, HOME).

I can provide a PR, if you think this is helpful.

Best regards,
David

**Comment by iomarmochtar** [comment]
Hi @dwieland ,

Yes it's intended. these are the reasons:
- Quoted from [Zen Of Python](https://peps.python.org/pep-0020/) "Explicit is better than implicit". by mentioned the required environment vars means we know exactly what env that used/consumed by the script. so in some cases can lead to easier to debug.
- Passing the env var contents from the parent process is supported by the version [0.4.0](https://github.com/iomarmochtar/gitlab-token-updater/blob/main/CHANGELOG.md#040), i think you can utilize that as well, eg:

```yaml
...
          - type: exec_cmd
            args:
              path: ./to/script.sh
              env:
                HOME: "${HOME}"
                PATH: "${PATH}"
```
